server:
   port: 8000
spring:
   application:
      name: springcloud-learn-api-service-member
eureka:
   client:
      service-url:
         defaultZone: http://127.0.0.1:8092/eureka,http://localhost:8091/eureka
      register-with-eureka: true
      fetch-registry: true
   instance:
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in seconds: 2
